replicaCount: 1

image:
  repository: "211125349493.dkr.ecr.us-east-1.amazonaws.com/capstone-team-project"
  tag: "8"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

djangoConfig:
  ALLOWED_HOSTS: "*"
  # DATABASE_URL: "sqlite:////db.sqlite3"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_NAME: "tododb"
  DB_USER: "admin"
  DB_PORT: "5432"
  DEBUG: "True"
  DJANGO_SETTINGS_MODULE: "config.settings"
  PYTHONPATH: "/app"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75
  targetMemoryUtilizationPercentage: 85

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

podSecurityContext:
  fsGroup: 1000
    
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
