# organization
sonar.organization=vladshein
# uniq key
sonar.projectKey=capstone
# path to source  (use comma if several path)
sonar.sources=frontend/src,backend/
# exlude (files, which dont need use)
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**
# encoding
sonar.sourceEncoding=UTF-8