replicaCount: 2

image:
  repository: "211125349493.dkr.ecr.us-east-1.amazonaws.com/dev-backend"
  tag: "8"
  pullPolicy: IfNotPresent

env:
  PORT: "5000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "capstone_db"
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"
  FRONTEND_URL: "http://a85d022f9af1e4981ace003ed41c2458-984925192.us-east-1.elb.amazonaws.com"
  POSTGRES_USER: "test"
  POSTGRES_PASSWOR: "Test#123"
  DATABASE_USERNAME: "test"
  DATABASE_PASSWORD: "Test#123"
  DATABASE_NAME: "capstone_db"
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_DIALECT: "postgres"
  REDIS_HOST: "valkey"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  TRUST_PROXY: true
  JWT_SECRET: "asdafsdfdsfsdfdsfsdfsd"
  JWT_REFRESH_SECRET: "zdsfsdfsdfsdfsdsd"
  JWT_EMAIL_VERIFICATION_SECRET: "zdfsdfdsfsdfsdf"
  JWT_PASSWORD_RESET_SECRET: "asdsdfdsfsdfsdfsdfsd"
  ACME_EMAIL: "admin@zmina.pp.ua"
  FRONTEND_DOMAIN: "http://a85d022f9af1e4981ace003ed41c2458-984925192.us-east-1.elb.amazonaws.com"
  VITE_API_URL: "http://a85d022f9af1e4981ace003ed41c2458-984925192.us-east-1.elb.amazonaws.com/api"
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_SECURE: true
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_FROM: ""

service:
  type: ClusterIP
  port: 5000