replicaCount: 2

image:
  repository: ""
  tag: "latest"

env:
  PORT: "5000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "capstone_db"
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"

service:
  type: ClusterIP
  port: 5000