replicaCount: 2

image:
  repository: "211125349493.dkr.ecr.us-east-1.amazonaws.com/dev-backend"
  tag: "8"

env:
  PORT: "5000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "capstone_db"
  VALKEY_HOST: "valkey"
  VALKEY_PORT: "6379"
  FRONTEND_URL: "http://a85d022f9af1e4981ace003ed41c2458-984925192.us-east-1.elb.amazonaws.com"

service:
  type: ClusterIP
  port: 5000