{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "YourSecurePasswordHere"
{{- end }}