apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migration-{{ .Release.Revision }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python", "manage.py", "migrate", "--noinput"]
        env:
        {{- toYaml .Values.djangoConfig | nindent 8 }}
      restartPolicy: Never
  backoffLimit: 2