apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle-worker
  labels:
    app: lifecycle-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lifecycle-worker
  template:
    metadata:
      labels:
        app: lifecycle-worker
    spec:
      containers:
        - name: lifecycle-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}