{{- range $app := list "backend" "frontend" "lifecycle-worker" "postgres" "valkey" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/vladshein/capstone-team-project.git'
    targetRevision: cloud-infra
    path: infra/charts/{{ $app }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}