apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/vladshein/capstone-team-project.git'
    targetRevision: HEAD
    path: charts/ # forder for charts with services
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true