apiVersion: v1
kind: Secret
metadata:
  name: capstone-app-repo-config
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.repoURL | quote }}