replicaCount: 1

image:
  repository: <your-aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/capstone-team-project-frontend
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer # або NodePort / ClusterIP (якщо використовується Ingress)
  port: 5173

env:
  VITE_API_URL: "http://backend:5000"