replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer #  NodePort / ClusterIP (if Ingress)
  port: 5173

env:
  VITE_API_URL: "http://backend:5000"