replicaCount: 1

image:
  repository: "211125349493.dkr.ecr.us-east-1.amazonaws.com/dev-frontend"
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5173

env:
  VITE_API_URL: "/api"