apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
    app: valkey
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: valkey
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: valkey-data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: {{ include "valkey.fullname" . }}-pvc
      {{- end }}