name: Deploy to VPS

# auto - with we merge main
# on:
#  push:
#    branches:
#      - main

# by hands (push button)
on:
  workflow_dispatch:      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /srv/capstone-app
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build frontend backend lifecycle-worker
            docker image prune -f
